(add-to-list 'load-path "~/.emacs.d/t-lisp")

(require 't-package)
(require 't-basic)
(require 't-func)
(require 't-helm)
(require 't-complete)
(require 't-projectile)
(require 't-mac)
(require 't-edit)
(require 't-looks)
(require 't-theme)
(require 't-yasnippet)
(require 't-lang-c)
(require 't-md)
(require 't-perl)
(require 't-git)
(require 't-js)
(require 't-web)
(require 't-css)
(require 't-lisp)
(require 't-org)

(el-get 'sync)
(provide 't-init)
